<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Shailesh kale</title>
    <link rel="stylesheet" href="bolg/all-bolgs/all-bolgs.css">
</head>

<body>
    <div class="container">
        <div class="sideber" id="sideber">
            <nav>
                <ul>
                <li><a href="/index.PHP">Home</a></li>
                    <li><a href="/info/info.PHP">My intre</a></li>
                    <li><a href="/services/services.PHP">Services</a></li>
                    <li><a href="/bolg/bolg.PHP">Blog</a></li>
                    <li><a href="/contact/contact.PHP">Contact Me</a></li>
                </ul>
            </nav>
        </div>
        <div class="main">
            <div class="container">
                <div class="BolgContainer">
                    <div class="divBolg">
                        <div class="Bolg" id="Bolg">
                            <img src="/bolg/image/C programming.jpg" alt="HTML">
                            <h2 id="H2_C_Programming">C Programming</h2>
                            <h3 id="H3_C_Programming">What is C Programming Langauge?</h3>
                            <p>
                            <h1>C</h1> is a general-purpose programming language that is extremely popular, simple, and
                            flexible to use. It is a structured programming language that is machine-independent and
                            extensively used to write various applications, Operating Systems like Windows, and many
                            other complex programs like Oracle database, Git, Python interpreter, and more.
                            </p>
                            <p>
                                It is said that ‘C’ is a god’s programming language. One can say, C is a base for the
                                programming. If you know ‘C,’ you can easily grasp the knowledge of the other
                                programming languages that uses the concept of ‘C’
                            </p>
                            <h1>History of C language</h1>
                            <p>
                                The base or father of programming languages is ‘ALGOL.’ It was first introduced in 1960.
                                ‘ALGOL’ was used on a large basis in European countries. ‘ALGOL’ introduced the concept
                                of structured programming to the developer community. In 1967, a new computer
                                programming language was announced called as ‘BCPL’ which stands for Basic Combined
                                Programming Language. BCPL was designed and developed by Martin Richards, especially for
                                writing system software. This was the era of programming languages. Just after three
                                years, in 1970 a new programming language called ‘B’ was introduced by Ken Thompson that
                                contained multiple features of ‘BCPL.’ This programming language was created using UNIX
                                operating system at AT&T and Bell Laboratories. Both the ‘BCPL’ and ‘B’ were system
                                programming languages.
                            </p>
                            <img id="c_img" src="/bolg/image/012419_1229_WhatisCProg2.jpg" alt="">
                            <p id="bolg-page">
                                In 1972, a great computer scientist Dennis Ritchie created a new programming language
                                called ‘C’ at the Bell Laboratories. It was created from ‘ALGOL’, ‘BCPL’ and ‘B’
                                programming languages. ‘C’ programming language contains all the features of these
                                languages and many more additional concepts that make it unique from other languages.
                            </p>
                            <p id="bolg-page">
                                ‘C’ is a powerful programming language which is strongly associated with the UNIX
                                operating system. Even most of the UNIX operating system is coded in ‘C’. Initially ‘C’
                                programming was limited to the UNIX operating system, but as it started spreading around
                                the world, it became commercial, and many compilers were released for cross-platform
                                systems. Today ‘C’ runs under a variety of operating systems and hardware platforms. As
                                it started evolving many different versions of the language were released. At times it
                                became difficult for the developers to keep up with the latest version as the systems
                                were running under the older versions. To assure that ‘C’ language will remain standard,
                                American National Standards Institute (ANSI) defined a commercial standard for ‘C’
                                language in 1989. Later, it was approved by the International Standards Organization
                                (ISO) in 1990. ‘C’ programming language is also called as ‘ANSI C’.
                            </p>
                            <!-- <button class="btn">Read More</button> -->
                            <hr>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

</html>