<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Shailesh kale</title>
    <link rel="stylesheet" href="bolg/all-bolgs/all-bolgs.css">
</head>

<body>
    <div class="container">
        <div class="sideber">
            <nav>
                <ul>
                <li><a href="/index.PHP">Home</a></li>
                    <li><a href="/info/info.PHP">My intre</a></li>
                    <li><a href="/services/services.PHP">Services</a></li>
                    <li><a href="/bolg/bolg.PHP">Blog</a></li>
                    <li><a href="/contact/contact.PHP">Contact Me</a></li>
                </ul>
            </nav>
        </div>
        <div class="main">
            <div class="container">
                <div class="BolgContainer">
                    <div class="divBolg">
                        <div class="Bolg" id="Bolg">
                            <img src="bolg/image/html.jpg" alt="HTML">
                            <h2>HTML</h2>
                            <h3>what is HTML ?</h3>
                            <p>
                                HTML stands for HyperText Markup Language, which can be a confusing term for many
                                beginners. The best way to explain HTML is to examine the meaning of each word.
                            </p>
                            <p> HyperText refers to text that contains links to other texts. Every time you click on a
                                highlighted or underlined link that takes you to another page, you are using hypertext.
                                As more and more pages use hypertext to link to each other, a “web” of pages starts to
                                form. This is where we get the term World Wide Web.</p>
                            <p>
                                Markup refers to the special symbols or codes that are inserted into a document to tell
                                the web browser how to display the document data. For example, markup code may tell the
                                browser to display a phrase in bold or italic text, or may tell the browser which parts
                                of the document are headings and which are paragraphs. HTML is just one of a number of
                                languages that uses markup code.
                            </p>
                            <p>
                                Language refers to the idea that the code is standardized. Just like regular spoken
                                languages, there are certain rules that everyone must follow when writing HTML. This is
                                so that all browsers can understand and interpret the code. There are many different
                                programming languages, and you may have heard of some of the popular ones such as Java,
                                Python and Ruby. Each language has its own unique set of rules, and many languages can
                                be used in combination with HTML to create amazing webpages and applications.
                            </p>
                            <p>
                                If we put these three definitions together, we could say that HTML is “a programming
                                language that uses unique code which allows you to display linked documents in a
                                browser”.</p>
                                <!-- <button class="btn">Read More</button> -->
                            <hr>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

</html>